#!/usr/bin/env python3
"""LibCST-based import + call-site rewriter for /repository-architect Phase 4.

Usage:
  rewrite-imports.py --symbol-map <path> --batch <N> --operation "<label>" [--dry-run]

Reads a symbol-map JSON (output of Phase 2 design) and rewrites BOTH:
  1. import statements (`from old import X` -> `from new import X`,
     `import old` -> `import new`, `import old as alias` -> `import new as alias`)
  2. attribute-access call sites (`old.X(args)` -> `new.X(args)`,
     `old.SUBMOD.X` -> `new.SUBMOD.X`)

across the tree.  Uses a hand-rolled cst.CSTTransformer (not the
Remove/Add visitor pair, which would silently no-op because the symbol
is still in use).

Symbol-map JSON shape (one record per moved symbol or module):

  [
    {
      "batch": 1,
      "operation": "Introduce panels/ subpackage",
      "kind": "module",                  # "module" | "symbol"
      "from": "appearance_panel",        # source module dotted path
      "to":   "panels.appearance",       # target module dotted path
      "symbol": null                      # only for kind=symbol (e.g. "AppearancePanel")
    },
    ...
  ]

INTENTIONALLY conservative: if LibCST is not installed, exit 2 with a
clear message rather than falling back to regex (per scout-C anti-pattern
R6: sed/regex are forbidden for Python import rewrites).

Use --dry-run to preview without modifying files.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, ValueError):
    pass


REPO_ROOT = Path(__file__).resolve().parents[3]

# Paths (relative to REPO_ROOT) excluded from the file walker.
# These are infrastructure, tooling-self, or generated directories that must
# never be rewritten by the codemod.  Checked as prefix matches on the
# POSIX-style relative path string.
_WALK_EXCLUSION_PREFIXES = (
    ".venv/",
    ".git/",
    ".claude/",        # self-modification guard (r2 execution-critic MED-1)
    ".github/",        # CI/CD — out of scope
    "plans/",          # historical design artefacts — read-only
    "__pycache__/",    # generated bytecode
)


def _dotted_to_attribute(cst_mod, dotted: str):
    """Convert a dotted string like 'panels.appearance' to a CST Attribute/Name node."""
    parts = dotted.split(".")
    node = cst_mod.Name(parts[0])
    for part in parts[1:]:
        node = cst_mod.Attribute(value=node, attr=cst_mod.Name(part))
    return node


def _attribute_dotted_path(node) -> str | None:
    """Read back a CST Name/Attribute chain into a dotted path string.

    Returns None if the node is not a pure name/attribute chain.
    """
    parts = []
    while True:
        if hasattr(node, "attr") and hasattr(node, "value"):
            parts.append(node.attr.value)
            node = node.value
        elif hasattr(node, "value") and isinstance(node.value, str):
            parts.append(node.value)
            return ".".join(reversed(parts))
        else:
            return None


def _build_transformer(
    cst_mod,
    metadata_mod,
    module_renames: dict[str, str],
    symbol_renames: dict[tuple[str, str], str],
):
    """Build a CSTTransformer that rewrites imports + attribute-access call sites.

    Args:
        cst_mod: the imported ``libcst`` module.
        metadata_mod: the imported ``libcst.metadata`` module.
        module_renames: {old_dotted: new_dotted} — for kind=module entries.
        symbol_renames: {(old_module, symbol_name): new_module} — for kind=symbol
            entries.  One entry per (source-module, symbol) pair.  Multiple symbols
            from the same source module may map to DIFFERENT destinations (e.g.
            ``surfaces.ParamSpec -> varieties.types`` and
            ``surfaces.VARIETIES -> varieties.registry``).
    """
    QualifiedNameProvider = metadata_mod.QualifiedNameProvider

    class Rewriter(cst_mod.CSTTransformer):
        # QualifiedNameProvider resolves import aliases to their canonical
        # fully-qualified names.  This allows leave_Name to detect that a bare
        # ``ParamSpec`` reference (after ``from surfaces import ParamSpec``) maps
        # to ``surfaces.ParamSpec`` — the string-matching approach in the original
        # code missed this case and also conflated multi-destination moves.
        METADATA_DEPENDENCIES = (QualifiedNameProvider,)

        def leave_SimpleStatementLine(self, original_node, updated_node):
            """Handle `from <module> import A, B, C` with multi-alias splitting.

            When a single ``from X import A, B`` statement has aliases that map to
            DIFFERENT destination modules (e.g. ``A -> dest1`` and ``B -> dest2``),
            the original node must be split into multiple ``from`` statements.
            ``FlattenSentinel`` is returned to expand one line into many.

            Aliases that do NOT appear in the symbol-map are left on the original
            source module (unchanged).
            """
            if len(updated_node.body) != 1:
                return updated_node
            stmt = updated_node.body[0]
            if not isinstance(stmt, cst_mod.ImportFrom):
                return updated_node
            if stmt.module is None:
                return updated_node
            if isinstance(stmt.names, cst_mod.ImportStar):
                return updated_node

            mod_path = _attribute_dotted_path(stmt.module)
            if mod_path is None:
                return updated_node

            # ---- Whole-module rename (kind=module) ----
            if mod_path in module_renames:
                new_mod = module_renames[mod_path]
                new_stmt = stmt.with_changes(module=_dotted_to_attribute(cst_mod, new_mod))
                return updated_node.with_changes(body=[new_stmt])

            # ---- Per-symbol rename (kind=symbol) ----
            # Check if this source module has any symbol entries.
            relevant = {sym: dest for (src, sym), dest in symbol_renames.items() if src == mod_path}
            if not relevant:
                return updated_node

            # Group aliases by their destination module.
            # Unmapped aliases stay on the original source module.
            groups: dict[str, list] = {}  # dest_module -> [ImportAlias, ...]
            for alias in stmt.names:
                if not isinstance(alias.name, cst_mod.Name):
                    # Complex alias name — leave unchanged on source module
                    groups.setdefault(mod_path, []).append(alias)
                    continue
                sym_name = alias.name.value
                dest = relevant.get(sym_name)
                if dest is not None:
                    groups.setdefault(dest, []).append(alias)
                else:
                    groups.setdefault(mod_path, []).append(alias)

            if len(groups) == 1 and mod_path not in groups:
                # All aliases map to the same single new destination — simple rename.
                only_dest = next(iter(groups))
                cleaned = _strip_trailing_comma(cst_mod, list(groups[only_dest]))
                new_stmt = stmt.with_changes(
                    module=_dotted_to_attribute(cst_mod, only_dest),
                    names=cleaned,
                )
                return updated_node.with_changes(body=[new_stmt])

            if len(groups) == 1:
                # All aliases stay on original module (none matched).
                return updated_node

            # Multiple destination groups — split into one statement per group.
            result = []
            for dest_mod, aliases in groups.items():
                cleaned = _strip_trailing_comma(cst_mod, aliases)
                new_stmt = stmt.with_changes(
                    module=_dotted_to_attribute(cst_mod, dest_mod),
                    names=cleaned,
                )
                result.append(updated_node.with_changes(body=[new_stmt]))
            return cst_mod.FlattenSentinel(result)

        def leave_Import(self, original_node, updated_node):
            """Handle `import old`, `import old as alias`, `import old.sub`."""
            new_names = []
            changed = False
            for alias in updated_node.names:
                mod_path = _attribute_dotted_path(alias.name)
                if mod_path is None:
                    new_names.append(alias)
                    continue
                if mod_path in module_renames:
                    new_mod = module_renames[mod_path]
                    new_names.append(alias.with_changes(name=_dotted_to_attribute(cst_mod, new_mod)))
                    changed = True
                else:
                    new_names.append(alias)
            if changed:
                return updated_node.with_changes(names=new_names)
            return updated_node

        def leave_Attribute(self, original_node, updated_node):
            """Rewrite attribute-access call sites.

            Handles two cases:
            1. Module rename: ``old.X`` -> ``new.X`` (e.g. ``appearance_panel.Foo``).
            2. Symbol rename: ``old_module.SymbolName`` -> ``new_module.SymbolName``
               (e.g. ``surfaces.ParamSpec`` -> ``varieties.types.ParamSpec``).

            Walks bottom-up (LibCST default) so only rewrites the LEAF of the
            attribute chain to avoid double-rewriting nested accesses.
            """
            chain = _attribute_dotted_path(updated_node)
            if chain is None:
                return updated_node

            # --- Module rename (kind=module) ---
            for old, new in sorted(module_renames.items(), key=lambda kv: -len(kv[0])):
                if chain == old or chain.startswith(old + "."):
                    suffix = chain[len(old):]  # includes leading "." or empty
                    new_chain = new + suffix
                    return _dotted_to_attribute(cst_mod, new_chain)

            # --- Symbol rename (kind=symbol): `surfaces.ParamSpec` -> `varieties.types.ParamSpec` ---
            # Split at first dot to extract (module_prefix, rest_of_chain).
            dot_idx = chain.find(".")
            if dot_idx == -1:
                return updated_node
            src_mod = chain[:dot_idx]
            rest = chain[dot_idx + 1:]  # may be "ParamSpec" or "ParamSpec.something"
            # The directly-accessed symbol is the first component of rest.
            sym_name = rest.split(".")[0]
            dest = symbol_renames.get((src_mod, sym_name))
            if dest is not None:
                new_chain = dest + "." + rest
                return _dotted_to_attribute(cst_mod, new_chain)

            return updated_node

        def leave_Name(self, original_node, updated_node):
            """Rewrite bare Name references for symbol-rename case.

            After ``from surfaces import ParamSpec``, a bare ``ParamSpec`` in the
            code body resolves to ``surfaces.ParamSpec`` via QualifiedNameProvider.
            If we're moving ``ParamSpec`` to ``varieties.types``, the ``from``
            statement is already rewritten by ``leave_SimpleStatementLine``.  The
            bare ``ParamSpec`` reference remains valid (the ``from`` import now
            points at the new module), so we do NOT rename the bare reference —
            only attribute-access references (``surfaces.ParamSpec``) need
            rewriting.

            This method is retained with METADATA_DEPENDENCIES wired up so that
            future callers can use ``QualifiedNameProvider.has_name(self, node,
            "old.Symbol")`` for context-sensitive checks.  Currently it is a
            no-op pass-through.
            """
            return updated_node

    return Rewriter()


def _strip_trailing_comma(cst_mod, aliases: list):
    """Remove the trailing Comma from the last ImportAlias in a list."""
    if not aliases:
        return aliases
    last = aliases[-1]
    return aliases[:-1] + [last.with_changes(comma=cst_mod.MaybeSentinel.DEFAULT)]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--symbol-map", required=True)
    parser.add_argument("--batch", type=int, required=True)
    parser.add_argument("--operation", required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    try:
        import libcst as cst
        import libcst.metadata as cst_metadata
    except ImportError:
        print("ERROR: libcst is not installed.", file=sys.stderr)
        print("  Please add `libcst` to requirements.txt and re-run.", file=sys.stderr)
        print("  Per scout-C anti-pattern R6: sed/regex are forbidden for Python import rewrites.", file=sys.stderr)
        sys.exit(2)

    smap_path = Path(args.symbol_map)
    if not smap_path.is_absolute():
        smap_path = REPO_ROOT / smap_path
    if not smap_path.exists():
        sys.exit(f"symbol-map not found: {smap_path}")

    full_map = json.loads(smap_path.read_text(encoding="utf-8"))
    batch_entries = [e for e in full_map if e.get("batch") == args.batch]
    if not batch_entries:
        sys.exit(f"no symbol-map entries for batch {args.batch}")

    # Partition entries by kind.
    module_renames: dict[str, str] = {}
    # symbol_renames: (old_module, symbol_name) -> new_module
    # Keyed by (src, sym) to support multiple symbols from the same source
    # module mapping to DIFFERENT destination modules (e.g. surfaces.ParamSpec ->
    # varieties.types AND surfaces.VARIETIES -> varieties.registry).
    symbol_renames: dict[tuple[str, str], str] = {}
    for e in batch_entries:
        kind = e.get("kind")
        if kind == "module":
            module_renames[e["from"]] = e["to"]
        elif kind == "symbol":
            old_module = e["from"]
            new_module = e["to"]
            symbol = e.get("symbol")
            if not symbol:
                print(f"  WARN: kind=symbol entry missing 'symbol' key; skipping: {e}", file=sys.stderr)
                continue
            symbol_renames[(old_module, symbol)] = new_module
        else:
            print(f"  WARN: unknown kind {kind!r} in symbol-map entry; skipping", file=sys.stderr)

    print(f"Rewriting imports + call sites for batch {args.batch}: {args.operation}")
    print(f"  Module renames: {len(module_renames)}, symbol renames: {len(symbol_renames)}")
    if args.dry_run:
        print("  [DRY RUN -- no files will be modified]")

    targets = []
    for p in REPO_ROOT.rglob("*.py"):
        rel = p.relative_to(REPO_ROOT).as_posix()
        # Exclude infrastructure, tooling, and generated paths (r2 execution-critic MED-1).
        excluded = any(rel.startswith(prefix) for prefix in _WALK_EXCLUSION_PREFIXES)
        # Also exclude any path that contains __pycache__ as a component.
        if not excluded and "__pycache__" in rel:
            excluded = True
        if excluded:
            continue
        # Don't rewrite the shim files themselves (they live at the OLD paths and
        # are SUPPOSED to reference the NEW path explicitly).
        if rel in module_renames.values():
            continue
        targets.append(p)

    modified = 0
    transformer = _build_transformer(cst, cst_metadata, module_renames, symbol_renames)
    for tgt in targets:
        try:
            src_text = tgt.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"  SKIP {tgt}: {exc}")
            continue

        try:
            tree = cst.parse_module(src_text)
        except cst.ParserSyntaxError as exc:
            print(f"  SKIP {tgt} (parse error): {exc}")
            continue

        # Wrap with MetadataWrapper to provide QualifiedNameProvider resolution.
        # This enables has_name() checks in the transformer.
        try:
            wrapper = cst_metadata.MetadataWrapper(tree)
        except Exception as exc:  # noqa: BLE001
            print(f"  SKIP {tgt} (metadata wrapper error): {exc}", file=sys.stderr)
            continue

        try:
            new_tree = wrapper.visit(transformer)
        except Exception as exc:  # noqa: BLE001
            print(f"  ERROR rewriting {tgt}: {exc}", file=sys.stderr)
            continue

        if new_tree.code == src_text:
            continue

        if not args.dry_run:
            tgt.write_text(new_tree.code, encoding="utf-8")
        modified += 1
        rel = tgt.relative_to(REPO_ROOT).as_posix()
        print(f"  {'[dry] ' if args.dry_run else ''}rewrote: {rel}")

    print(f"Done. {modified} files {'would be ' if args.dry_run else ''}modified.")


if __name__ == "__main__":
    main()
